name = "medical-innovation-agent"
main = "backend/index.ts"
compatibility_date = "2024-10-14"
compatibility_flags = ["nodejs_compat"]

[observability]
enabled = true

# Workers AI binding
[ai]
binding = "AI"
remote = true

# D1 Database
[[d1_databases]]
binding = "DB"
database_name = "medical-innovation-db"
database_id = "" # Fill after: wrangler d1 create medical-innovation-db
preview_database_id = "local-db" # Use local database for dev

# R2 Storage
[[r2_buckets]]
binding = "R2"
bucket_name = "medical-innovation-files"
preview_bucket_name = "medical-innovation-files-preview" # Use local bucket for dev

# Durable Objects
[durable_objects]
bindings = [
  { name = "InteractionAgent", class_name = "InteractionAgent" },
  { name = "ResearchAgent", class_name = "ResearchAgent" }
]

[[migrations]]
tag = "v1"
new_sqlite_classes = ["InteractionAgent", "ResearchAgent"]

# Environment variables (add to .dev.vars for local)
[vars]
ENVIRONMENT = "development"

